// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3RZbx1FjWUdRSdisPZ42GxRyNms67qQQ',
    appId: '1:74545766342:web:e02c9bbfe48156d2eadcc7',
    messagingSenderId: '74545766342',
    projectId: 'stock-tracker-app-42903',
    authDomain: 'stock-tracker-app-42903.firebaseapp.com',
    storageBucket: 'stock-tracker-app-42903.firebasestorage.app',
    measurementId: 'G-XXVKGLXRGB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9ate9CtyAJWEur_ZoBoK4hsAzcSfPMv4',
    appId: '1:74545766342:android:66e930fc7b1324caeadcc7',
    messagingSenderId: '74545766342',
    projectId: 'stock-tracker-app-42903',
    storageBucket: 'stock-tracker-app-42903.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDb532E8r4V9tl4BjO5KL1yHEE3FSevRqs',
    appId: '1:74545766342:ios:11799f42481d8f5ceadcc7',
    messagingSenderId: '74545766342',
    projectId: 'stock-tracker-app-42903',
    storageBucket: 'stock-tracker-app-42903.firebasestorage.app',
    iosBundleId: 'com.example.stocktrackerAppProject2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDb532E8r4V9tl4BjO5KL1yHEE3FSevRqs',
    appId: '1:74545766342:ios:11799f42481d8f5ceadcc7',
    messagingSenderId: '74545766342',
    projectId: 'stock-tracker-app-42903',
    storageBucket: 'stock-tracker-app-42903.firebasestorage.app',
    iosBundleId: 'com.example.stocktrackerAppProject2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3RZbx1FjWUdRSdisPZ42GxRyNms67qQQ',
    appId: '1:74545766342:web:89f8c28ddb94874beadcc7',
    messagingSenderId: '74545766342',
    projectId: 'stock-tracker-app-42903',
    authDomain: 'stock-tracker-app-42903.firebaseapp.com',
    storageBucket: 'stock-tracker-app-42903.firebasestorage.app',
    measurementId: 'G-0GWPBYT33N',
  );
}
